INSERT INTO author VALUES(null, "F. Scott Fitzgerald");
INSERT INTO author VALUES(null, "John Steinbeck");
INSERT INTO author VALUES(null, "George Orwell");
INSERT INTO author VALUES(null, "James Joyce");
INSERT INTO author VALUES(null, "Vladimir Nabokov");
INSERT INTO author VALUES(null, "Joseph Heller");
INSERT INTO author VALUES(null, "J. D. Salinger");
INSERT INTO author VALUES(null, "Toni Morrison");
INSERT INTO author VALUES(null, "William Faulkner");
INSERT INTO author VALUES(null, "Harper Lee");
INSERT INTO author VALUES(null, "J. R. R. Tolkien");
INSERT INTO author VALUES(null, "Gabriel García Márquez");
INSERT INTO author VALUES(null, "Aldous Huxley");
INSERT INTO author VALUES(null, "Virginia Woolf");
INSERT INTO author VALUES(null, "Ralph Ellison");
INSERT INTO author VALUES(null, "Margaret Mitchell");
INSERT INTO author VALUES(null, "Charlotte Brontë");
INSERT INTO author VALUES(null, "Jack Kerouac");
INSERT INTO author VALUES(null, "Jane Austen");
INSERT INTO author VALUES(null, "William Golding");
INSERT INTO author VALUES(null, "George Eliot");
INSERT INTO author VALUES(null, "Leo Tolstoy");
INSERT INTO author VALUES(null, "E. M. Forster");
INSERT INTO author VALUES(null, "Marcel Proust");
INSERT INTO author VALUES(null, "Emily Brontë");
INSERT INTO author VALUES(null, "C. S. Lewis");
INSERT INTO author VALUES(null, "Alice Walker");
INSERT INTO author VALUES(null, "Salman Rushdie");
INSERT INTO author VALUES(null, "A. A. Milne");
INSERT INTO author VALUES(null, "Joseph Conrad");
INSERT INTO author VALUES(null, "Kurt Vonnegut");
INSERT INTO author VALUES(null, "Herman Melville");
INSERT INTO author VALUES(null, "Louisa May Alcott");
INSERT INTO author VALUES(null, "Richard Wright");
INSERT INTO author VALUES(null, "Douglas Adams");
INSERT INTO author VALUES(null, "Charles Dickens");
INSERT INTO author VALUES(null, "Ernest Hemingway");
INSERT INTO author VALUES(null, "Daphne du Maurier");
INSERT INTO author VALUES(null, "Albert Camus");
INSERT INTO author VALUES(null, "Lewis Carroll");
INSERT INTO author VALUES(null, "Gustave Flaubert");
INSERT INTO author VALUES(null, "Kenneth Grahame");
INSERT INTO author VALUES(null, "Margaret Atwood");
INSERT INTO author VALUES(null, "Thomas Hardy");
INSERT INTO author VALUES(null, "Zora Neale Hurston");
INSERT INTO author VALUES(null, "John Irving");
INSERT INTO author VALUES(null, "Henry James");
INSERT INTO author VALUES(null, "Franz Kafka");
INSERT INTO author VALUES(null, "Fyodor Dostoyevsky");
INSERT INTO author VALUES(null, "Anthony Burgess");
INSERT INTO author VALUES(null, "Edith Wharton");
INSERT INTO author VALUES(null, "Miguel de Cervantes");
INSERT INTO author VALUES(null, "Philip Pullman");
INSERT INTO author VALUES(null, "Evelyn Waugh");
INSERT INTO author VALUES(null, "Doris Lessing");
INSERT INTO author VALUES(null, "Mark Twain");
INSERT INTO author VALUES(null, "Chinua Achebe");
INSERT INTO author VALUES(null, "Henry Fielding");
INSERT INTO author VALUES(null, "J. K. Rowling");
INSERT INTO author VALUES(null, " The Unnamable");
INSERT INTO author VALUES(null, "Laurence Sterne");
INSERT INTO author VALUES(null, "E. B. White");
INSERT INTO author VALUES(null, "D. H. Lawrence");
INSERT INTO author VALUES(null, "Sebastian Faulks");
INSERT INTO author VALUES(null, "Jonathan Swift");
INSERT INTO author VALUES(null, "Richard Adams");
INSERT INTO author VALUES(null, "Thomas Pynchon");
INSERT INTO author VALUES(null, "Mary Shelley");
INSERT INTO author VALUES(null, "Samuel Richardson");
INSERT INTO author VALUES(null, "Frank Herbert");
INSERT INTO author VALUES(null, "Daniel Defoe");
INSERT INTO author VALUES(null, "James Baldwin");
INSERT INTO author VALUES(null, "Robert Penn Warren");
INSERT INTO author VALUES(null, "Thomas Mann");
INSERT INTO author VALUES(null, "Jack London");
INSERT INTO author VALUES(null, "Günter Grass");
INSERT INTO author VALUES(null, "John Dos Passos");
INSERT INTO author VALUES(null, "Malcolm Lowry");
INSERT INTO author VALUES(null, "J. M. Coetzee");
INSERT INTO author VALUES(null, "Anne Frank");
INSERT INTO author VALUES(null, "Nathaniel Hawthorne");
INSERT INTO author VALUES(null, "Louis de Bernières");
INSERT INTO author VALUES(null, "Carson McCullers");
INSERT INTO author VALUES(null, "William Makepeace Thackeray");
INSERT INTO author VALUES(null, "Dante Alighieri");
INSERT INTO author VALUES(null, "Alexandre Dumas");
INSERT INTO author VALUES(null, "Theodore Dreiser");
INSERT INTO author VALUES(null, "Don DeLillo");
INSERT INTO author VALUES(null, "Ian McEwan");
INSERT INTO author VALUES(null, "Fyodor Dostoevsky");
INSERT INTO author VALUES(null, "Ford Madox Ford");
INSERT INTO author VALUES(null, "Umberto Eco");
INSERT INTO author VALUES(null, "Annie Proulx");
INSERT INTO author VALUES(null, "Wilkie Collins");
INSERT INTO author VALUES(null, "Saul Bellow");
INSERT INTO author VALUES(null, "Andre Gide");
INSERT INTO author VALUES(null, "Willa Cather");
INSERT INTO author VALUES(null, "KJV");
INSERT INTO author VALUES(null, "Jean Rhys");
INSERT INTO author VALUES(null, "Kazuo Ishiguro");
INSERT INTO author VALUES(null, "Raymond Chandler");
INSERT INTO author VALUES(null, "Robert Graves");
INSERT INTO author VALUES(null, "Henry Miller");
INSERT INTO author VALUES(null, "Louis-Ferdinand Céline");
INSERT INTO author VALUES(null, "H. G. Wells");
INSERT INTO author VALUES(null, "Vikram Seth");
INSERT INTO author VALUES(null, "A.S. Byatt");
INSERT INTO author VALUES(null, "John Kennedy Toole");
INSERT INTO author VALUES(null, "Sylvia Plath");
INSERT INTO author VALUES(null, "Samuel Beckett");
INSERT INTO author VALUES(null, "Junot Diaz");
INSERT INTO author VALUES(null, "Jean-Paul Sartre");
INSERT INTO author VALUES(null, "Jane Smiley");
INSERT INTO author VALUES(null, "Michael Chabon");
INSERT INTO author VALUES(null, "Aleksandr Solzhenitsyn");
INSERT INTO author VALUES(null, "Roald Dahl");
INSERT INTO author VALUES(null, "William Gaddis");
INSERT INTO author VALUES(null, "Herodotus");
INSERT INTO author VALUES(null, "Boris Pasternak");
INSERT INTO author VALUES(null, "Kingsley Amis");
INSERT INTO author VALUES(null, "Italo Calvino");
INSERT INTO author VALUES(null, "Georges Perec");
INSERT INTO author VALUES(null, "Mikhail Bulgakov");
INSERT INTO author VALUES(null, "Pearl S. Buck");
INSERT INTO author VALUES(null, "William J. Kennedy");
INSERT INTO author VALUES(null, "Anthony Powell");
INSERT INTO author VALUES(null, "Milan Kundera");
INSERT INTO author VALUES(null, "Rudyard Kipling");
INSERT INTO author VALUES(null, "Graham Greene");
INSERT INTO author VALUES(null, "Ken Kesey");
INSERT INTO author VALUES(null, "V. S. Naipaul");
INSERT INTO author VALUES(null, "Sir Arthur Conan Doyle");
INSERT INTO author VALUES(null, "Marilynne Robinson");
INSERT INTO author VALUES(null, "William Styron");
INSERT INTO author VALUES(null, "François Mauriac");
INSERT INTO author VALUES(null, "Michael Shaara");
INSERT INTO author VALUES(null, "L. M. Montgomery");
INSERT INTO author VALUES(null, "Primo Levi");
INSERT INTO author VALUES(null, "Thornton Wilder");
INSERT INTO author VALUES(null, "Jorge Luis Borges");
INSERT INTO author VALUES(null, "Thomas Keneally");
INSERT INTO author VALUES(null, "Muriel Spark");
INSERT INTO author VALUES(null, "Robert Louis Stevenson");
INSERT INTO author VALUES(null, "Antoine de Saint-Exupéry");
INSERT INTO author VALUES(null, "Stephen Crane");
INSERT INTO author VALUES(null, "Homer");
INSERT INTO author VALUES(null, "Arthur Golden");
INSERT INTO author VALUES(null, "Murasaki Shikibu");
INSERT INTO author VALUES(null, "Yann Martel");
INSERT INTO author VALUES(null, "John Bunyan");
INSERT INTO author VALUES(null, "Luigi Pirandello");
INSERT INTO author VALUES(null, "Nathanael West");
INSERT INTO author VALUES(null, "Stephen King");
INSERT INTO author VALUES(null, "W.G. Sebald");
INSERT INTO author VALUES(null, "Robert Coover");
INSERT INTO author VALUES(null, "Haruki Murakami");
INSERT INTO author VALUES(null, "Andre Malraux");
INSERT INTO author VALUES(null, "Nikolai Gogol");
INSERT INTO author VALUES(null, "John Updike");
INSERT INTO author VALUES(null, "Flannery O'Connor");
INSERT INTO author VALUES(null, "Gertrude Stein");
INSERT INTO author VALUES(null, "J. G. Ballard");
INSERT INTO author VALUES(null, "Hermann Hesse");
INSERT INTO author VALUES(null, "Arthur Koestler");
INSERT INTO author VALUES(null, "William S. Burroughs");
INSERT INTO author VALUES(null, "Pierre Choderlos de Laclos");
INSERT INTO author VALUES(null, "Alain-Fournier");
INSERT INTO author VALUES(null, "Sherwood Anderson");
INSERT INTO author VALUES(null, "Boris Vian");
INSERT INTO author VALUES(null, "Irvine Welsh");
INSERT INTO author VALUES(null, "Walker Percy");
INSERT INTO author VALUES(null, "Geoffrey Chaucer");
INSERT INTO author VALUES(null, "Sinclair Lewis");
INSERT INTO author VALUES(null, "Raymond Federman");
INSERT INTO author VALUES(null, "Jung Chang");
INSERT INTO author VALUES(null, "Thomas Love Peacock");
INSERT INTO author VALUES(null, "Orhan Pamuk");
INSERT INTO author VALUES(null, "Simone de Beauvoir");
INSERT INTO author VALUES(null, "Kate Chopin");
INSERT INTO author VALUES(null, "James Jones");
INSERT INTO author VALUES(null, "Honoré de Balzac");
INSERT INTO author VALUES(null, "Robert Musil");
INSERT INTO author VALUES(null, "Samuel Butler");
INSERT INTO author VALUES(null, "John Cheever");
INSERT INTO author VALUES(null, "Stephen Wright");
INSERT INTO author VALUES(null, "Stendhal");
INSERT INTO author VALUES(null, "Heinrich Böll");
INSERT INTO author VALUES(null, "William Shakespeare");
INSERT INTO author VALUES(null, "Naguib Mahfouz");
INSERT INTO author VALUES(null, "Robert A. Heinlein");
INSERT INTO author VALUES(null, "Truman Capote");
INSERT INTO author VALUES(null, "P. G. Wodehouse");
INSERT INTO author VALUES(null, "Benjamin Disraeli");
INSERT INTO author VALUES(null, "William H. Gass");
INSERT INTO author VALUES(null, "Jacques Prévert");
INSERT INTO author VALUES(null, "Dashiell Hammett");
INSERT INTO author VALUES(null, "Guillaume Apollinaire");
INSERT INTO author VALUES(null, "John Fowles");
INSERT INTO author VALUES(null, "Selma Lagerlöf");
INSERT INTO author VALUES(null, "Hergé");
INSERT INTO author VALUES(null, "Norman Mailer");
INSERT INTO author VALUES(null, "Knut Hamsun");
INSERT INTO author VALUES(null, "Audrey Niffenegger");
INSERT INTO author VALUES(null, "Madeleine L'Engle");
INSERT INTO author VALUES(null, "Victor Hugo");
INSERT INTO author VALUES(null, "Claude Lévi-Strauss");
INSERT INTO author VALUES(null, "Tsao Hsueh-Chin");
INSERT INTO author VALUES(null, "Joan Didion");
INSERT INTO author VALUES(null, "Peter Carey");
INSERT INTO author VALUES(null, "J. M. G. Le Clezio");
INSERT INTO author VALUES(null, "John O'Hara");
INSERT INTO author VALUES(null, "Patrick Suskind");
INSERT INTO author VALUES(null, "Frances Hodgson Burnett");
INSERT INTO author VALUES(null, "René Goscinny");
INSERT INTO author VALUES(null, "Iain Banks");
INSERT INTO author VALUES(null, "Ayn Rand");
INSERT INTO author VALUES(null, "Eugene Ionesco");
INSERT INTO author VALUES(null, "Émile Zola");
INSERT INTO author VALUES(null, "Roddy Doyle");
INSERT INTO author VALUES(null, "Donald Barthelme");
INSERT INTO author VALUES(null, "Sigmund Freud");
INSERT INTO author VALUES(null, "Frank McCourt");
INSERT INTO author VALUES(null, "Marguerite Yourcenar");
INSERT INTO author VALUES(null, "Anthony Trollope");
INSERT INTO author VALUES(null, "William Vollmann");
INSERT INTO author VALUES(null, "Alexis de Tocqueville");
INSERT INTO author VALUES(null, "Elizabeth Gaskell");
INSERT INTO author VALUES(null, "Ray Bradbury");
INSERT INTO author VALUES(null, "Charles Darwin");
INSERT INTO author VALUES(null, "Dino Buzzati");
INSERT INTO author VALUES(null, "James T. Farrell");
INSERT INTO author VALUES(null, "Jean-Jacques Rousseau");
INSERT INTO author VALUES(null, "Amitav Ghosh");
INSERT INTO author VALUES(null, "Philip Roth");
INSERT INTO author VALUES(null, "Gene Wolfe");
INSERT INTO author VALUES(null, "Karl Marx");
INSERT INTO author VALUES(null, "Laurie Lee");
INSERT INTO author VALUES(null, "Niccolò Machiavelli");
INSERT INTO author VALUES(null, "Jean Giono");
INSERT INTO author VALUES(null, "Irene Nemirovsky");
INSERT INTO author VALUES(null, "Tracy Kidder");
INSERT INTO author VALUES(null, "Stella Gibbons");
INSERT INTO author VALUES(null, "Jacqueline Wilson");
INSERT INTO author VALUES(null, "Wallace Stegner");
INSERT INTO author VALUES(null, "Saint Augustine");
INSERT INTO author VALUES(null, "Albert Cohen");
INSERT INTO author VALUES(null, "Nevil Shute");
INSERT INTO author VALUES(null, "Neil Gaiman");
INSERT INTO author VALUES(null, "Jerome K. Jerome");
INSERT INTO author VALUES(null, "Thomas Hobbes");
INSERT INTO author VALUES(null, "Robert Tressell");
INSERT INTO author VALUES(null, "Dorothy Allison");
INSERT INTO author VALUES(null, "Iris Murdoch");
INSERT INTO author VALUES(null, "Ken Follett");
INSERT INTO author VALUES(null, "Samuel R. Delany");
INSERT INTO author VALUES(null, "Arthur Ransome");
INSERT INTO author VALUES(null, "Thucydides");
INSERT INTO author VALUES(null, "Oscar Wilde");
INSERT INTO author VALUES(null, "George Grossmith");
INSERT INTO author VALUES(null, "Rikki Ducornet");
INSERT INTO author VALUES(null, "Yasunari Kawabata");
INSERT INTO author VALUES(null, "Keri Hulme");
INSERT INTO author VALUES(null, "Arundhati Roy");
INSERT INTO author VALUES(null, "Raymond Queneau");
INSERT INTO author VALUES(null, "William Gibson");
INSERT INTO author VALUES(null, "E. L. Doctorow");
INSERT INTO author VALUES(null, "Khaled Hosseini");
INSERT INTO author VALUES(null, "Stefan Zweig");
INSERT INTO author VALUES(null, "Ursula K. Le Guin");
INSERT INTO author VALUES(null, "Erskine Childers");
INSERT INTO author VALUES(null, "Mervyn Peake");
INSERT INTO author VALUES(null, "Donna Tartt");
INSERT INTO author VALUES(null, "Joseph McElroy");
INSERT INTO author VALUES(null, "Rosamunde Pilcher");
INSERT INTO author VALUES(null, "Alexander Solzhenitsyn");
INSERT INTO author VALUES(null, "Henry Roth");
INSERT INTO author VALUES(null, "Françoise Sagan");
INSERT INTO author VALUES(null, "Jostein Gaarder");
INSERT INTO author VALUES(null, "Dan Brown");
INSERT INTO author VALUES(null, "John Barth");
INSERT INTO author VALUES(null, "Vercors");
INSERT INTO author VALUES(null, "Helen Fielding");
INSERT INTO author VALUES(null, "James Dickey");
INSERT INTO author VALUES(null, "Paul Metcalf");
INSERT INTO author VALUES(null, "David Guterson");
INSERT INTO author VALUES(null, "Ivan Turgenev");
INSERT INTO author VALUES(null, "W. E. B. Du Bois");
INSERT INTO author VALUES(null, "John Buchan");
INSERT INTO author VALUES(null, "Upton Sinclair");
INSERT INTO author VALUES(null, "Georges Bernanos");
INSERT INTO author VALUES(null, "Alain Robbe-Grillet");
INSERT INTO author VALUES(null, "Erich Maria Remarque");
INSERT INTO author VALUES(null, "Tom Wolfe");
INSERT INTO author VALUES(null, "Norton Juster");
INSERT INTO author VALUES(null, "Saint-John Perse");
INSERT INTO author VALUES(null, "Isabel Allende");
INSERT INTO author VALUES(null, "John Milton");
INSERT INTO author VALUES(null, "L. Frank Baum");
INSERT INTO author VALUES(null, "Flann O'Brien");
INSERT INTO author VALUES(null, "Alberto Moravia");
INSERT INTO author VALUES(null, "Patricia C. Wrede");
INSERT INTO author VALUES(null, "Cormac McCarthy");
INSERT INTO author VALUES(null, "Rabindranath Tagore");
INSERT INTO author VALUES(null, "Arthur C. Clarke");
INSERT INTO author VALUES(null, "John Hawkes");
INSERT INTO author VALUES(null, "Colleen McCullough");
INSERT INTO author VALUES(null, "Agatha Christie");
INSERT INTO author VALUES(null, "Michelle Magorian");
INSERT INTO author VALUES(null, "André Breton");
INSERT INTO author VALUES(null, "Booth Tarkington");
INSERT INTO author VALUES(null, "Louis Aragon");
INSERT INTO author VALUES(null, "James McBride");
INSERT INTO author VALUES(null, "Paul Claudel");
INSERT INTO author VALUES(null, "Walt Whitman");
INSERT INTO author VALUES(null, "Bret Easton Ellis");
INSERT INTO author VALUES(null, "Barbara Kingsolver");
INSERT INTO author VALUES(null, "Djuna Barnes");
INSERT INTO author VALUES(null, "Nick Hornby");
INSERT INTO author VALUES(null, "Hunter S. Thompson");
INSERT INTO author VALUES(null, "Jeffrey Archer");
INSERT INTO author VALUES(null, "Bertolt Brecht");
INSERT INTO author VALUES(null, "Enid Blyton");
INSERT INTO author VALUES(null, "Andrei Bely");
INSERT INTO author VALUES(null, "Paul Auster");
INSERT INTO author VALUES(null, "Alan Moore");
INSERT INTO author VALUES(null, "Michel Tournier");
INSERT INTO author VALUES(null, "Carlos Ruiz Zafón");
INSERT INTO author VALUES(null, "Nancy Mitford");
INSERT INTO author VALUES(null, "Madame de La Fayette");
INSERT INTO author VALUES(null, "Anna Sewell");
INSERT INTO author VALUES(null, "Roberto Bolaño");
INSERT INTO author VALUES(null, "Martin Amis");
INSERT INTO author VALUES(null, "David Foster Wallace");
INSERT INTO author VALUES(null, "Eoin Colfer");
INSERT INTO author VALUES(null, "Colette");
INSERT INTO author VALUES(null, "Mark Haddon");
INSERT INTO author VALUES(null, "Max Beerbohm");
INSERT INTO author VALUES(null, "Vera Brittain");
INSERT INTO author VALUES(null, "Paul Eluard");
INSERT INTO author VALUES(null, "Betty Smith");
INSERT INTO author VALUES(null, "Chimamanda Ngozi Adichie");
INSERT INTO author VALUES(null, "Malorie Blackman");
INSERT INTO author VALUES(null, "Giuseppe Di Lampedusa");
INSERT INTO author VALUES(null, "Lawrence Durrell");
INSERT INTO author VALUES(null, "Hugo Pratt");
INSERT INTO author VALUES(null, "Raymond Carver");
INSERT INTO author VALUES(null, "Roland Barthes");
INSERT INTO author VALUES(null, "Jean Toomer");
INSERT INTO author VALUES(null, "Alice Sebold");
INSERT INTO author VALUES(null, "Armistead Maupin");
INSERT INTO author VALUES(null, "Amy Tan");
INSERT INTO author VALUES(null, "Terry Pratchett");
INSERT INTO author VALUES(null, "Julien Gracq");
INSERT INTO author VALUES(null, "Michel Foucault");
INSERT INTO author VALUES(null, "Russell Hoban");
INSERT INTO author VALUES(null, "W. Somerset Maugham");
INSERT INTO author VALUES(null, "William Eastlake");
INSERT INTO author VALUES(null, "John Knowles");
INSERT INTO author VALUES(null, "Bram Stoker");
INSERT INTO author VALUES(null, "Stanley Elkin");
INSERT INTO author VALUES(null, "Robert M. Pirsig");
INSERT INTO author VALUES(null, "Grace Paley");
INSERT INTO author VALUES(null, "Kaye Gibbons");
INSERT INTO author VALUES(null, "John le Carré");
INSERT INTO author VALUES(null, "Alfred Döblin");
INSERT INTO author VALUES(null, "Olive Ann Burns");
INSERT INTO author VALUES(null, "Thomas Wolfe");
INSERT INTO author VALUES(null, "Tom Robbins");
INSERT INTO author VALUES(null, "Richard Hughes");
INSERT INTO author VALUES(null, "Abdelrahman Munif");
INSERT INTO author VALUES(null, "Dave Eggers");
INSERT INTO author VALUES(null, "Marguerite Duras");
INSERT INTO author VALUES(null, "Carlos Fuentes");
INSERT INTO author VALUES(null, "Herman Wouk");
INSERT INTO author VALUES(null, "Anne Tyler");
INSERT INTO author VALUES(null, "Ben Marcus");
INSERT INTO author VALUES(null, "Johann Wolfgang von Goethe");
INSERT INTO author VALUES(null, "Maurice Sendak");
INSERT INTO author VALUES(null, "Nathalie Sarraute");
INSERT INTO author VALUES(null, "Harry Mathews");
INSERT INTO author VALUES(null, "Mario Puzo");
INSERT INTO author VALUES(null, "Richard Fariña");
INSERT INTO author VALUES(null, "R. K. Narayan");
INSERT INTO author VALUES(null, "Jules Renard");
INSERT INTO author VALUES(null, "Bill Bryson");
INSERT INTO author VALUES(null, "James A. Michener");
INSERT INTO author VALUES(null, "Philip K. Dick");
INSERT INTO author VALUES(null, "Elie Wiesel");
INSERT INTO author VALUES(null, "Jacques Lacan");
INSERT INTO author VALUES(null, "Rachel Carson");
INSERT INTO author VALUES(null, "Wendell Berry");
INSERT INTO author VALUES(null, "Elizabeth Taylor");
INSERT INTO author VALUES(null, "Jill Ker Conway");
INSERT INTO author VALUES(null, "Antonin Artaud");
INSERT INTO author VALUES(null, "John Crowley");
INSERT INTO author VALUES(null, "Stephen Hawking");
INSERT INTO author VALUES(null, "Voltaire");
INSERT INTO author VALUES(null, "Paul Bowles");
INSERT INTO author VALUES(null, "Anonymous");
INSERT INTO author VALUES(null, "Jack Finney");
INSERT INTO author VALUES(null, "Blaise Cendrars");
INSERT INTO author VALUES(null, "Beryl Bainbridge");
INSERT INTO author VALUES(null, "David Mitchell");
INSERT INTO author VALUES(null, "Howard Pyle");
INSERT INTO author VALUES(null, "Ismail Kadare");
INSERT INTO author VALUES(null, "Dodie Smith");
INSERT INTO author VALUES(null, "Ivan Goncharov");
INSERT INTO author VALUES(null, "Delia Smith");
INSERT INTO author VALUES(null, "Federico García Lorca");
INSERT INTO author VALUES(null, "Louis Sachar");
INSERT INTO author VALUES(null, "Alexander Theroux");
INSERT INTO author VALUES(null, "Walter Scott");
INSERT INTO author VALUES(null, "Georges Simenon");
INSERT INTO author VALUES(null, "Elizabeth Bowen");
INSERT INTO author VALUES(null, "Brian Keenan");
INSERT INTO author VALUES(null, "Jean Genet");
INSERT INTO author VALUES(null, "Ronald Sukenick");
INSERT INTO author VALUES(null, "Rohinton Mistry");
INSERT INTO author VALUES(null, "Ishmael Reed");
INSERT INTO author VALUES(null, "Alasdair Gray");
INSERT INTO author VALUES(null, "René Char");
INSERT INTO author VALUES(null, "Arnold Bennett");
INSERT INTO author VALUES(null, "Henry Adams");
INSERT INTO author VALUES(null, "Alessandro Manzoni");
INSERT INTO author VALUES(null, "James Fenimore Cooper");
INSERT INTO author VALUES(null, "Mitch Albom");
INSERT INTO author VALUES(null, "Mao Tse-Tung");
INSERT INTO author VALUES(null, "Alexander Pushkin");
INSERT INTO author VALUES(null, "Caleb Carr");
INSERT INTO author VALUES(null, "Harriet Beecher Stowe");
INSERT INTO author VALUES(null, "Raymond E. Feist");
INSERT INTO author VALUES(null, "Elizabeth Berg");
INSERT INTO author VALUES(null, "Henry Green");
INSERT INTO author VALUES(null, "James Hadley Chase");
INSERT INTO author VALUES(null, "William James");
INSERT INTO author VALUES(null, "Edgar P. Jacobs");
INSERT INTO author VALUES(null, "Steve Katz");
INSERT INTO author VALUES(null, "Erskine Caldwell");
INSERT INTO author VALUES(null, "Rainer Maria Rilke");
INSERT INTO author VALUES(null, "Richard Dawkins");
INSERT INTO author VALUES(null, "Robin McKinley");
INSERT INTO author VALUES(null, "Rita Mae Brown");
INSERT INTO author VALUES(null, "Michael Crichton");
INSERT INTO author VALUES(null, "Michel Butor");
INSERT INTO author VALUES(null, "John Maynard Keynes");
INSERT INTO author VALUES(null, "Jean M. Auel");
INSERT INTO author VALUES(null, "Theodore Sturgeon");
INSERT INTO author VALUES(null, "Hannah Arendt");
INSERT INTO author VALUES(null, "Pat Conroy");
INSERT INTO author VALUES(null, "Paulo Coelho");
INSERT INTO author VALUES(null, "Alan Paton");
INSERT INTO author VALUES(null, "Gilbert Sorrentino");
INSERT INTO author VALUES(null, "James Ellroy");
INSERT INTO author VALUES(null, "John Kenneth Galbraith");
INSERT INTO author VALUES(null, "Anya Seton");
INSERT INTO author VALUES(null, "Angela Carter");
INSERT INTO author VALUES(null, "Richard Burton");
INSERT INTO author VALUES(null, "Howard Zinn");
INSERT INTO author VALUES(null, "Jaroslav Hasek");
INSERT INTO author VALUES(null, "Malcolm X");
INSERT INTO author VALUES(null, "Ted Mooney");
INSERT INTO author VALUES(null, "James M. Cain");
INSERT INTO author VALUES(null, "André Franquin");
INSERT INTO author VALUES(null, "Steve Erickson");
INSERT INTO author VALUES(null, "Lytton Strachey");
INSERT INTO author VALUES(null, "J. P. Donleavy");
INSERT INTO author VALUES(null, "Kathy Acker");
INSERT INTO author VALUES(null, "Meg Cabot");
INSERT INTO author VALUES(null, "Winston S. Churchill");
INSERT INTO author VALUES(null, "Forrest Carter");
INSERT INTO author VALUES(null, "Nicholas Evans");