INSERT INTO publisher VALUES(null, "Interlink Publishing Online");
INSERT INTO publisher VALUES(null, "Steerforth Press");
INSERT INTO publisher VALUES(null, "Catbird Press");
INSERT INTO publisher VALUES(null, "Overlook Press");
INSERT INTO publisher VALUES(null, "Picador UK");
INSERT INTO publisher VALUES(null, "Northwestern University Press");
INSERT INTO publisher VALUES(null, "Indiana University Press");
INSERT INTO publisher VALUES(null, "Creation Books");
INSERT INTO publisher VALUES(null, "English");
INSERT INTO publisher VALUES(null, "Page information");
INSERT INTO publisher VALUES(null, "Wikidata item");
INSERT INTO publisher VALUES(null, "Simple talk");
INSERT INTO publisher VALUES(null, "Disclaimers");
INSERT INTO publisher VALUES(null, "Paulist Press");
INSERT INTO publisher VALUES(null, "Penguin Classics");
INSERT INTO publisher VALUES(null, "Atlas Press");
INSERT INTO publisher VALUES(null, "Show any page");
INSERT INTO publisher VALUES(null, "Harvard University Press");
INSERT INTO publisher VALUES(null, "University of Chicago Press");
INSERT INTO publisher VALUES(null, "MIT Press");
INSERT INTO publisher VALUES(null, "Welcome to Random House");
INSERT INTO publisher VALUES(null, "Developers");
INSERT INTO publisher VALUES(null, "Central European University Press");
INSERT INTO publisher VALUES(null, "Thames & Hudson (USA)");
INSERT INTO publisher VALUES(null, "Godine Publishing");
INSERT INTO publisher VALUES(null, "Ivan R. Dee");
INSERT INTO publisher VALUES(null, "Vintage Books at Random House (UK)");
INSERT INTO publisher VALUES(null, "Open Court Book");
INSERT INTO publisher VALUES(null, "Upload file");
INSERT INTO publisher VALUES(null, "Hesperus press");
INSERT INTO publisher VALUES(null, "Tuttle Publishing");
INSERT INTO publisher VALUES(null, "Dover Publications");
INSERT INTO publisher VALUES(null, "Text is available under the Creative Commons Attri");
INSERT INTO publisher VALUES(null, "Mobile view");
INSERT INTO publisher VALUES(null, "University of California Press Books");
INSERT INTO publisher VALUES(null, "Wordsworth Editions Website");
INSERT INTO publisher VALUES(null, "Hackett");
INSERT INTO publisher VALUES(null, "Enable previews");
INSERT INTO publisher VALUES(null, "Copper Canyon Press");
INSERT INTO publisher VALUES(null, "Download as PDF");
INSERT INTO publisher VALUES(null, "Duckworth Online");
INSERT INTO publisher VALUES(null, "About Wikipedia");
INSERT INTO publisher VALUES(null, "Thames & Hudson (UK)");
INSERT INTO publisher VALUES(null, "randomhouse.com (US)");
INSERT INTO publisher VALUES(null, "Pan Macmillan");
INSERT INTO publisher VALUES(null, "Read");
INSERT INTO publisher VALUES(null, "Continuum - Athlone");
INSERT INTO publisher VALUES(null, "What links here");
INSERT INTO publisher VALUES(null, "Main page");
INSERT INTO publisher VALUES(null, "Page for printing");
INSERT INTO publisher VALUES(null, "Da Capo Press");
INSERT INTO publisher VALUES(null, "Prometheus Books");
INSERT INTO publisher VALUES(null, "University of Nebraska Press");
INSERT INTO publisher VALUES(null, "Bison Books");
INSERT INTO publisher VALUES(null, "Create account");
INSERT INTO publisher VALUES(null, "View history");
INSERT INTO publisher VALUES(null, "Belknap Press of Harvard University Press");
INSERT INTO publisher VALUES(null, "Wisdom Publications");
INSERT INTO publisher VALUES(null, "Samuel Beckett");
INSERT INTO publisher VALUES(null, "Yale University Press");
INSERT INTO publisher VALUES(null, "Smith and Kraus Publishers");
INSERT INTO publisher VALUES(null, "W.W. Norton & Company");
INSERT INTO publisher VALUES(null, "University of Toronto Medieval Texts");
INSERT INTO publisher VALUES(null, "Scholastic Inc.");
INSERT INTO publisher VALUES(null, "Station Hill Press");
INSERT INTO publisher VALUES(null, "Open Court");
INSERT INTO publisher VALUES(null, "Counterpoint Press");
INSERT INTO publisher VALUES(null, "Make a book");
INSERT INTO publisher VALUES(null, "Glas New Russian Writing");
INSERT INTO publisher VALUES(null, "Ardis Books Homepage");
INSERT INTO publisher VALUES(null, "Phaidon Press");
INSERT INTO publisher VALUES(null, "Pimlico Books at Random House");
INSERT INTO publisher VALUES(null, "Athlone Books");
INSERT INTO publisher VALUES(null, "Cookie statement");
INSERT INTO publisher VALUES(null, "Give to Wikipedia");
INSERT INTO publisher VALUES(null, "Farrar");
INSERT INTO publisher VALUES(null, "Kessinger Publishing");
INSERT INTO publisher VALUES(null, "Bloodaxe Books");
INSERT INTO publisher VALUES(null, "Arcade Publishing");
INSERT INTO publisher VALUES(null, "Related changes");
INSERT INTO publisher VALUES(null, "Carroll and Graf");
INSERT INTO publisher VALUES(null, "Talk");
INSERT INTO publisher VALUES(null, "Johns Hopkins University Press");
INSERT INTO publisher VALUES(null, "Anvil Press Poetry");
INSERT INTO publisher VALUES(null, "Ediciones Altovolta");
INSERT INTO publisher VALUES(null, "Stanford University Press");
INSERT INTO publisher VALUES(null, "Shanti Sadan Publications");
INSERT INTO publisher VALUES(null, "Verso Books");
INSERT INTO publisher VALUES(null, "Exact Change");
INSERT INTO publisher VALUES(null, "Cambridge University Press");
INSERT INTO publisher VALUES(null, "Inpress Books UK");
INSERT INTO publisher VALUES(null, "Penguin Group (USA)");
INSERT INTO publisher VALUES(null, "Publishing");
INSERT INTO publisher VALUES(null, "Oxford University Press - UK");
INSERT INTO publisher VALUES(null, "Oxford University Press - US");
INSERT INTO publisher VALUES(null, "Modern Library");
INSERT INTO publisher VALUES(null, "University of Minnesota Press");
INSERT INTO publisher VALUES(null, "City Lights Publishers");
INSERT INTO publisher VALUES(null, "Dalkey Archive Press");
INSERT INTO publisher VALUES(null, "Marion Boyars Online");
INSERT INTO publisher VALUES(null, "Princeton University Press");
INSERT INTO publisher VALUES(null, "Page");
INSERT INTO publisher VALUES(null, "Methuen");
INSERT INTO publisher VALUES(null, "Kodansha");
INSERT INTO publisher VALUES(null, "Zephyr Press");
INSERT INTO publisher VALUES(null, "Log in");
INSERT INTO publisher VALUES(null, "Routledge");
INSERT INTO publisher VALUES(null, "Help");
INSERT INTO publisher VALUES(null, "Detritus.com");
INSERT INTO publisher VALUES(null, "Permanent link");
INSERT INTO publisher VALUES(null, "Change");
INSERT INTO publisher VALUES(null, "HarperCollins Publishers");
INSERT INTO publisher VALUES(null, "iBooks, Inc.");
INSERT INTO publisher VALUES(null, "Carcanet");
INSERT INTO publisher VALUES(null, "Schocken Books");
INSERT INTO publisher VALUES(null, "Black Sparrow Books");
INSERT INTO publisher VALUES(null, "Lists");
INSERT INTO publisher VALUES(null, "Basic Books");
INSERT INTO publisher VALUES(null, "Shambhala Publications");
INSERT INTO publisher VALUES(null, "Dedalus Books");
INSERT INTO publisher VALUES(null, "New Directions Publishing");
INSERT INTO publisher VALUES(null, "Peter Owen Publishers");
INSERT INTO publisher VALUES(null, "Bloomsbury.com - Home page");
INSERT INTO publisher VALUES(null, "The New Press");
INSERT INTO publisher VALUES(null, "This page was last changed on 21 June 2013, at 01:");
INSERT INTO publisher VALUES(null, "Contributions");
INSERT INTO publisher VALUES(null, "Phoenix Press history reprints");
INSERT INTO publisher VALUES(null, "Picador USA");
INSERT INTO publisher VALUES(null, "Hrvatski");
INSERT INTO publisher VALUES(null, "Pathfinder Books");
INSERT INTO publisher VALUES(null, "Special pages");
INSERT INTO publisher VALUES(null, "Simple start");
INSERT INTO publisher VALUES(null, "NYRB Classics");
INSERT INTO publisher VALUES(null, "Privacy policy");
INSERT INTO publisher VALUES(null, "Calder Publications");
INSERT INTO publisher VALUES(null, "Random House UK");
INSERT INTO publisher VALUES(null, "Pantheon Books at Random House");
INSERT INTO publisher VALUES(null, "Oomf, Inc.");
INSERT INTO publisher VALUES(null, "Sun & Moon");
INSERT INTO publisher VALUES(null, "Stone Bridge Press");
INSERT INTO publisher VALUES(null, "SUNY Press");
INSERT INTO publisher VALUES(null, "New changes");
INSERT INTO publisher VALUES(null, "Change source");
INSERT INTO publisher VALUES(null, "Penguin UK");
INSERT INTO publisher VALUES(null, "CompanionGuides.com");
INSERT INTO publisher VALUES(null, "Twisted Spoon Press");
INSERT INTO publisher VALUES(null, "Borzoi Reader Classics");
INSERT INTO publisher VALUES(null, "Vintage (US)");
INSERT INTO publisher VALUES(null, "Harvill Press at Random House");
INSERT INTO publisher VALUES(null, "TASCHEN Books");
INSERT INTO publisher VALUES(null, "Cite this page");
INSERT INTO publisher VALUES(null, "Not logged in");
INSERT INTO publisher VALUES(null, "Grove Press / Atlantic Monthly Press");
INSERT INTO publisher VALUES(null, "Columbia University Press");
INSERT INTO publisher VALUES(null, "Malton House Press");